name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install    
    - run: npm run test
    
    - name: Init new repo in dist folder and commit generated files
      run: |
       cd target/site/serenity/
       git init
       git add -A
       git config --local user.email "action@github.com"
       git config --local user.name "GitHub Action"
       git commit -m 'deploy'
       
    - name: Force push to destination branch
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        exclude_assets: '.png,/bootstrap-treeview/dist/bootstrap-treeview.min.css,/bootstrap-treeview/dist/bootstrap-treeview.min.js'
        force: true
        directory: target/site/serenity/
        
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.2
      with:
          publish-dir: './target/site/serenity/'
          production-branch: gh-pages
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
      env:
          NETLIFY_AUTH_TOKEN: 'wpS8NssRJlLZ4XPIbvMystfcFcvGh2xcJvv4SceNzDI'
          NETLIFY_SITE_ID: '5304aaad-9095-4092-9889-743e4ab360a9'
      timeout-minutes: 1
